package com.mediassist.platform.audit.domain;

public enum AuditAction {
    CREATED,
    UPDATED,
    STATUS_CHANGED,
    UPLOADED,
    DOWNLOADED,
    ARCHIVED,
    EXTRACTION_STARTED,
    EXTRACTION_COMPLETED,
    EXTRACTION_FAILED,
    CHUNKING_STARTED,
    CHUNKING_COMPLETED,
    CHUNKING_FAILED,
    EMBEDDING_STARTED,
    EMBEDDING_COMPLETED,
    EMBEDDING_FAILED,
    SEMANTIC_SEARCH_PERFORMED
}
